/**
 * Maintainable Christian worship vocabulary and word-level pronunciation dictionary.
 * Maps words between Tamil, Roman pronunciation, and Devanagari representation.
 */

export const WORD_OVERRIDES = [
  // Core Divine Names & Titles
  { tamil: 'இயேசு', roman: 'Yeshu', hindi: 'येशु' },
  { tamil: 'இயேசுவே', roman: 'Yeshuvae', hindi: 'येशुवे' },
  { tamil: 'இயேசுவுக்கு', roman: 'Yeshuvukku', hindi: 'येशुवुक्कु' },
  { tamil: 'இயேசுவின்', roman: 'Yeshuvin', hindi: 'येशुविन' },
  { tamil: 'இயேஷு', roman: 'Yeshu', hindi: 'यीशु' },
  { tamil: 'கர்த்தர்', roman: 'Karththar', hindi: 'कर्त्तर' },
  { tamil: 'கர்த்தரே', roman: 'Karththarae', hindi: 'कर्त्तरे' },
  { tamil: 'கர்த்தருக்கு', roman: 'Karththarukku', hindi: 'कर्त्तरुक्कु' },
  { tamil: 'கர்த்தரின்', roman: 'Karththarin', hindi: 'कर्त्तरिन' },
  { tamil: 'தேவன்', roman: 'Dhevan', hindi: 'देवन' },
  { tamil: 'தேவனே', roman: 'Dhevanae', hindi: 'देवने' },
  { tamil: 'தேவனுக்கு', roman: 'Dhevanukku', hindi: 'देवनुक्कु' },
  { tamil: 'தேவனின்', roman: 'Dhevanin', hindi: 'देवनिन' },
  { tamil: 'ஆண்டவர்', roman: 'Aandavar', hindi: 'आण्डवर' },
  { tamil: 'ஆண்டவரே', roman: 'Aandavarae', hindi: 'आण्डवरे' },
  { tamil: 'ஆவியானவர்', roman: 'Aaviyaanavar', hindi: 'आवियानवर' },
  { tamil: 'ஆவியானவரே', roman: 'Aaviyaanavarae', hindi: 'आवियानवरे' },
  { tamil: 'பரிசுத்தர்', roman: 'Parisuththar', hindi: 'परिसुत्तर' },
  { tamil: 'பரிசுத்தரே', roman: 'Parisuththarae', hindi: 'परिसुत्तरे' },
  { tamil: 'பரிசுத்த', roman: 'Parisuththa', hindi: 'परिसुत्त' },
  { tamil: 'பிதா', roman: 'Pidhaa', hindi: 'पिदा' },
  { tamil: 'பிதாவே', roman: 'Pidhaavae', hindi: 'पिदावे' },
  { tamil: 'அப்பா', roman: 'Appaa', hindi: 'अप्पा' },
  { tamil: 'ராஜா', roman: 'Raajaa', hindi: 'राजा' },
  { tamil: 'ராஜாவே', roman: 'Raajaavae', hindi: 'राजावे' },
  { tamil: 'இரட்சகர்', roman: 'Ratchagar', hindi: 'रट्चगर' },
  { tamil: 'இரட்சகரே', roman: 'Ratchagarae', hindi: 'रट्चगरे' },
  { tamil: 'மேய்ப்பர்', roman: 'Meippar', hindi: 'मेय्प्पर' },
  { tamil: 'மேய்ப்பரே', roman: 'Meipparae', hindi: 'मेय्प्परे' },
  { tamil: 'கன்மலை', roman: 'Kanmalai', hindi: 'कन्मलै' },
  { tamil: 'கன்மலையானவரே', roman: 'Kanmalaiyaanavarae', hindi: 'कन्मलैयानवरे' },
  { tamil: 'உயிர்த்தெழுந்தவரே', roman: 'Uyirththezhundhavarae', hindi: 'उयिर्त्तेऴुन्दवरे' },

  // Worship, Praise & Thanks
  { tamil: 'ஆராதனை', roman: 'Aaraadhanai', hindi: 'आराधनै' },
  { tamil: 'ஆராதிப்பேன்', roman: 'Aaraadhippaen', hindi: 'आरादिप्पेन' },
  { tamil: 'ஆராதிக்கிறோம்', roman: 'Aaraadhikkiroam', hindi: 'आरादिक्किरोम' },
  { tamil: 'துதி', roman: 'Thudhi', hindi: 'तुदि' },
  { tamil: 'துதிகள்', roman: 'Thudhigal', hindi: 'तुदिगल' },
  { tamil: 'துதிக்கிறோம்', roman: 'Thudhikiroam', hindi: 'तुदिक्किरोम' },
  { tamil: 'ஸ்தோத்திரம்', roman: 'Sthoththiram', hindi: 'स्तोत्तिरम' },
  { tamil: 'ஸ்தோத்திரங்கள்', roman: 'Sthoththirangal', hindi: 'स्तोत्तिरङ्गल' },
  { tamil: 'தொத்த', roman: 'thoththa', hindi: 'तोत्त' },
  { tamil: 'மகிமை', roman: 'Magimai', hindi: 'महिमै' },
  { tamil: 'மகிமைப்படுத்துகிறோம்', roman: 'Magimaippaduththugiroam', hindi: 'महिमैप्परुत्तुगिरोम' },
  { tamil: 'கிருபை', roman: 'Kirubai', hindi: 'किरुबै' },
  { tamil: 'கிருபையும்', roman: 'Kirubaiyum', hindi: 'किरुबैयुम' },
  { tamil: 'இரக்கம்', roman: 'Irakkam', hindi: 'इरक्कम' },
  { tamil: 'அன்பு', roman: 'Anbu', hindi: 'अन्बु' },
  { tamil: 'அன்பானவரே', roman: 'Anbaanavarae', hindi: 'அन्बानवरे' },
  { tamil: 'நன்றி', roman: 'Nandri', hindi: 'नन्ड्री' },
  { tamil: 'அல்லேலூயா', roman: 'Hallelujah', hindi: 'हालेलुयाह' },
  { tamil: 'ஆமேன்', roman: 'Amen', hindi: 'आमीन' },
  { tamil: 'ஓசன்னா', roman: 'Hosanna', hindi: 'होसन्ना' },

  // Pronouns & Common Connectors
  { tamil: 'என்', roman: 'En', hindi: 'एन' },
  { tamil: 'என்னை', roman: 'Ennai', hindi: 'एन्नै' },
  { tamil: 'எனக்கு', roman: 'Enakku', hindi: 'एनक्कु' },
  { tamil: 'என்னில்', roman: 'Ennil', hindi: 'एन्निल' },
  { tamil: 'எந்தன்', roman: 'Enthan', hindi: 'एन्दन' },
  { tamil: 'என்மேல்', roman: 'Enmael', hindi: 'एनमेल' },
  { tamil: 'உம்மை', roman: 'Ummai', hindi: 'उम्मै' },
  { tamil: 'உமக்கே', roman: 'Umakkae', hindi: 'उमक्के' },
  { tamil: 'உமக்கு', roman: 'Umakku', hindi: 'उमक्कु' },
  { tamil: 'உந்தன்', roman: 'Undhan', hindi: 'उन्दन' },
  { tamil: 'உம்', roman: 'Um', hindi: 'उम' },
  { tamil: 'நீரே', roman: 'Neerae', hindi: 'नीरे' },
  { tamil: 'நீர்', roman: 'Neer', hindi: 'नीर' },
  { tamil: 'நாங்கள்', roman: 'Naangal', hindi: 'नाङ्गल' },
  { tamil: 'நாம்', roman: 'Naam', hindi: 'नाम' },
  { tamil: 'நான்', roman: 'Naan', hindi: 'नान' },
  { tamil: 'இல்லை', roman: 'Illai', hindi: 'इल्लै' },
  { tamil: 'மனதார', roman: 'Manadhaara', hindi: 'मनदार' },
  { tamil: 'என்றென்றும்', roman: 'Endrendrum', hindi: 'एन्ड्रेन्ड्रुम' },
  { tamil: 'வல்லமை', roman: 'Vallamai', hindi: 'वल्लमै' },
  { tamil: 'மாட்சிமை', roman: 'Maatchimai', hindi: 'माट्चिमै' },
  { tamil: 'நிறைந்தவரே', roman: 'Nirainthavarae', hindi: 'निरैन्दवरे' },
  { tamil: 'பாத்திரரே', roman: 'Paathirarae', hindi: 'पात्तिररे' },
  { tamil: 'தெய்வம்', roman: 'Deivam', hindi: 'देवम' },
  { tamil: 'சிலுவை', roman: 'Siluvai', hindi: 'सिलुवै' },
  { tamil: 'இரத்தம்', roman: 'Iraththam', hindi: 'इरत्तम' },
  { tamil: 'காக்கும்', roman: 'Kaakkum', hindi: 'काक्कुम' },
  { tamil: 'வல்லவரே', roman: 'Vallavarae', hindi: 'वल्लवरे' },
  { tamil: 'நல்லவரே', roman: 'Nallavarae', hindi: 'नल्लवरे' },

  // Hindi / Marathi Christian Vocabulary (Rulebook Exact Matches)
  { tamil: 'பிரபு', roman: 'Prabhu', hindi: 'प्रभु' },
  { tamil: 'மசீஹ்', roman: 'Maseeh', hindi: 'मसीह' },
  { tamil: 'ஆத்மா', roman: 'Aatma', hindi: 'आत्मा' },
  { tamil: 'பவித்ர', roman: 'Pavitra', hindi: 'पवित्र' },
  { tamil: 'அனுக்ரஹ்', roman: 'Anugrah', hindi: 'अनुग्रह' },
  { tamil: 'உத்தார்', roman: 'Uddhaar', hindi: 'उद्धार' },
  { tamil: 'க்ரூஸ்', roman: 'Kroos', hindi: 'क्रूस' },
  { tamil: 'ஆஷீஷ்', roman: 'Aashish', hindi: 'आशीष' },
  { tamil: 'ஆராதனா', roman: 'Aaraadhana', hindi: 'आराधना' },
  { tamil: 'ஸ்துதி', roman: 'Stuti', hindi: 'स्तुति' },
  { tamil: 'தன்யவாத்', roman: 'Dhanyavaad', hindi: 'धन्यवाद' },
  { tamil: 'விஷ்வாஸ்', roman: 'Vishvaas', hindi: 'विश्वास' },
  { tamil: 'ப்ரார்த்தனா', roman: 'Praarthana', hindi: 'प्रार्थना' },
  { tamil: 'மஹிமா', roman: 'Mahima', hindi: 'महिमा' },
  { tamil: 'ப்ரேம்', roman: 'Prem', hindi: 'प्रेम' },
  { tamil: 'அனந்த்', roman: 'Anant', hindi: 'अनन्त' },
  { tamil: 'ராஜா', roman: 'Raaja', hindi: 'राजा' },
  { tamil: 'பாத்ஷாஹ்', roman: 'Baadshaah', hindi: 'बादशाह' },
  { tamil: 'ஆபாரி', roman: 'Aabhaari', hindi: 'आभारी' },
  { tamil: 'ஆம்ஹி', roman: 'Aamhi', hindi: 'आम्ही' },
  { tamil: 'மான்தோ', roman: 'Maanto', hindi: 'मानतो' },
  { tamil: 'இயேசுலா', roman: 'Yeshula', hindi: 'येशुला' },
  { tamil: 'முஜ்மே', roman: 'Mujhmein', hindi: 'मुझमें' },
  { tamil: 'ஜீதா', roman: 'Jeeta', hindi: 'जीता' },
  { tamil: 'ஹே', roman: 'hai', hindi: 'है' },
  { tamil: 'ஹைன்', roman: 'hain', hindi: 'हैं' },
  { tamil: 'மே', roman: 'mein', hindi: 'में' },
  { tamil: 'நஹி', roman: 'nahin', hindi: 'नहीं' },
  { tamil: 'உட்டாயா', roman: 'uthaaya', hindi: 'उठाया' },
  { tamil: 'ஷைதான்', roman: 'shaitaan', hindi: 'शैतान' },
  { tamil: 'ஷப்த்', roman: 'shabd', hindi: 'शब्द' },
  { tamil: 'ஜக்மீ', roman: 'zakhmi', hindi: 'ज़ख्मी' },
  { tamil: 'ஜிந்தகீ', roman: 'zindagi', hindi: 'ज़िन्दगी' },
  { tamil: 'ஸ்பர்ஷ்', roman: 'sparsh', hindi: 'स्पर्श' },
  { tamil: 'ஸ்வபாவ்', roman: 'swabhaav', hindi: 'स्वभाव' },
  { tamil: 'பஸ்', roman: 'bas', hindi: 'बस' },
  { tamil: 'ச்சல்தா', roman: 'chalta', hindi: 'चलता' },
  { tamil: 'ச்சரண்', roman: 'charan', hindi: 'चरण' },
  { tamil: 'ச்சாஹே', roman: 'chaahe', hindi: 'चाहे' },
  { tamil: 'ச்சலா', roman: 'chala', hindi: 'चला' },
  { tamil: 'சச்சா', roman: 'sachcha', hindi: 'सच्चा' },
  { tamil: 'ஃபரிஷ்தா', roman: 'farishta', hindi: 'फ़रिश्ता' },
  { tamil: 'டர்தா', roman: 'darta', hindi: 'डरता' },
  { tamil: 'பர்தன்', roman: 'bartan', hindi: 'बर्तन' },
  { tamil: 'வஹான்', roman: 'wahaan', hindi: 'वहाँ' },
  { tamil: 'ப்யார்', roman: 'pyaar', hindi: 'प्यार' },
  { tamil: 'ஜூம்', roman: 'jhoom', hindi: 'झूम' },
  { tamil: 'நாம்', roman: 'naam', hindi: 'नाम' },
  { tamil: 'தில்', roman: 'dil', hindi: 'दिल' },
  { tamil: 'ஜீவன்', roman: 'jeevan', hindi: 'जीवन' },
  { tamil: 'துனியா', roman: 'duniya', hindi: 'दुनिया' },
  { tamil: 'மௌத்', roman: 'maut', hindi: 'मौत' },
  { tamil: 'வசன்', roman: 'vachan', hindi: 'वचन' }
];

// Lookup Maps
export const TAMIL_WORD_MAP = new Map();
export const ROMAN_WORD_MAP = new Map();
export const HINDI_WORD_MAP = new Map();

for (const entry of WORD_OVERRIDES) {
  if (entry.tamil) TAMIL_WORD_MAP.set(entry.tamil, entry);
  if (entry.roman) ROMAN_WORD_MAP.set(entry.roman.toLowerCase(), entry);
  if (entry.hindi) HINDI_WORD_MAP.set(entry.hindi, entry);
}
